# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4318de46f404da2e5cfcb8e18d7c0260d8b8c90bafa0803535f5bbd42da38e57f1bceeeb27c3e2e029e4c8eb11a51a6cafffe7a52291cef98edfc7b376026ce2

test:
  secret_key_base: 50bbb66a55d5b958f897fd2526c513bdd4bea2b41f993a85971835163f7ed1a94f87c28e3e6ae1fbb760d118b3f979e8419dd4736d1f679c136001483eedacce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
